# Generated by Django 3.1.5 on 2021-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlog', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopic',
            name='text',
        ),
        migrations.AddField(
            model_name='usertopic',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
