# Generated by Django 3.1.7 on 2021-03-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userlog', '0002_auto_20210330_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='tag_name',
        ),
    ]
