# Generated by Django 3.1.5 on 2021-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlog', '0003_auto_20210222_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopic',
            name='title',
        ),
        migrations.AddField(
            model_name='usertopic',
            name='text',
            field=models.CharField(default='DEFAULT VALUE', max_length=120),
        ),
    ]
